name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build -w back
          npm run build -w webapp
          npm run build -w cdk
        
      - name: Lint
        run: |
          npm run lint -w back
          npm run lint -w webapp
          npm run lint -w cdk

      - name: Test
        run: |
          npm run test -w back
          npm run test -w webapp

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          aws-region: ap-northeast-1

      - name: Deploy to AWS
        run: npm run deploy -w cdk
